name: Release challenge

on:
  push:
    tags:
      - '*'

jobs:
  build-and-release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set env
        run: echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: prepare challenge
        run: |
          /bin/bash prepare-challenge.sh
          tar czf challenge.tar.gz challenge
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "challenge.tar.gz"
